name: "API-Build-$(Date:dd:MM:yyyy)-$(Build.SourceBranchName)-$(Rev:r)"

trigger:
- main

pool: Self-hosted


stages:
- stage: Build
  jobs: 
  - job: Build
    steps:
    - task: Bash@3
      displayName: Build
      inputs:
        targetType: inline
        script: |
          echo Build Stage

  - job: Test
    dependsOn : Build
    steps:
    - task: Bash@3
      displayName: Test
      inputs:
        targetType: inline
        script: |
         echo Test

  - job: Deploy
    dependsOn: 
      - Build
      - Test
    steps:
      - task: Bash@3
        displayName: Deploy
        inputs:
          targetType: inline
          script: |
            echo Deploy